version: "3"

services:
  app:
    build:
      dockerfile: ./server/Dockerfile-dev
      context: .
    command: npm run dev

  database:
    ports:
      - "3306:3306"

  migration:
    build:
      dockerfile: ./migration/Dockerfile-dev
      context: .
